version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      POSTGRES_PASSWORD: ejemplo
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ejemplo

